### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by pabioFavanetto** [rdkcentral/ThunderJS#1]
Cannot find module '...................\ThunderJS-master\examples\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Can someone can help me with this error i don't understand.

**Comment by wouterlucas** [comment]
Are you trying to import the browser or module? And what are you importing into? 

I.e. are you doing this in node or a browser? Using ES6 modules? Or something else?
